version: "2"
services:
  go:
    build: "."
    ports:
      - 8080:8080
    container_name: "emoji"
  mysql:
    hostname: mysql
    image: mysql:5.6
    ports:
      - 3306:3306
    networks:
      - emoji
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
networks:
  emoji: