version: "2"
services:
  go:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9527:9527
    container_name: go
    depends_on:
      - mysql
    networks:
      - emoji
  mysql:
    container_name: mysql
    hostname: mysql:5.6
    image: mysql:5.6
    ports:
      - 3307:3306
    networks:
      - emoji
    environment:
      - MYSQL_ROOT_PASSWORD=zt147258369
      - TZ=Asia/Shanghai
    volumes:
      - "/home/www/emoji/mysql:/var/lib/mysql"
      - "./src : /var/lib/mysql/src"
networks:
  emoji:
    driver: bridge